name: flutter_dependency_draw
description: flutter_dependency_draw
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencyConst: &dependencyConst
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  common:
    path: ../common
  menu:
    path: ../menu
  order:
    path: ../order
  trade:
    path: ../trade
  cart:
    path: ../cart
  splash:
    path: ../splash
  upgrade:
    path: ../upgrade

dependencies:
  *dependencyConst

dependency_overrides:
  *dependencyConst


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  yaml: ^3.1.1
  gviz: ^0.4.0

flutter:
  uses-material-design: true
